### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by danilocecilia** [danielsneijers/react-flash-message#1]
Please fix type on the examples at this page:

"Massage" to "Message"

https://www.npmjs.com/package/react-flash-message

Thanks

**Comment by bcuz** [comment]
ya, this got me for a sec, too

**Comment by ravirajawasthi** [comment]
Yeah, code editor saved me

**Comment by danielsneijers** [comment]
Hi guys! It's been a while since updated this package, but the typo is fixed now on NPM, along with updating all the (dev)dependencies because of security reasons. Look for v1.0.3 on NPM
