### ISSUE TITLE
Can't open it

### ISSUE THREAD

**Issue by dliflcDavid** [danielsneijers/react-flash-message#13]
./src/App.js
Module not found: Can't resolve 'react-flash-message' in '/Users...

**Comment by starlord13599** [comment]
Facing the same issue, Did you find the solution to this??

**Comment by msabramo** [comment]
I have the same issue. This seems to be a problem in 1.0.7 and 1.0.6 but not 1.0.5. When I install 1.0.5 (`npm install react-flash-message@1.0.5`, I notice that the directory in `node_modules` has a `build` directory. With the broken versions, it does not. So it looks like maybe with the newer versions a build wasn't done before uploading the package or somehow else the `build` directory is getting excluded.

**Comment by danielsneijers** [comment]
Very sorry about missing this, I had the artefacts of older versions on my machine, but ignored by git. This is now fixed in v1.0.8
