### ISSUE TITLE
Module not found: Can't resolve 'react-flash-message'

### ISSUE THREAD

**Issue by gangaswamy** [danielsneijers/react-flash-message#14]
in your package.json it is pointing to build folder  but it is not there when it installs I think it is missing. please could you that back it was there in previous versions.

"main": "build/index.js",

**Comment by hsh0917** [comment]
I've got the same issue.

**Comment by sonisourabh** [comment]
Facing the same issue - spent several hours to realize that react-flash-message is the culprit, not my project settings.

**Comment by sonisourabh** [comment]
I solved the problem for me by using the library from a fork [react-flash-message](https://github.com/Looskie/react-flash-message)

- `yarn add https://github.com/Looskie/react-flash-message.git`

**Comment by dohaelee** [comment]
@sonisourabh I wasted 30 minutes on this issue. YOU ARE MY HERE!

**Comment by shime** [comment]
Facing the same issue.

**Comment by danielsneijers** [comment]
Very sorry about missing this, I had the artefacts of older versions on my machine, but ignored by git. This is now fixed in v1.0.8
